qe: use same uuidfilters on postgres and crdb
We only implemented the fix for postgres in
7e0dbcd28cc971c33e3b0852ecce79d20b35661f. This does the same for
cockroachdb. The test that was used to confirm that cockroachdb does not
support LIKE queries on UUID columns in the following:

```
You are now connected to database "test_uuid_like" as user "prisma".
test_uuid_like=> CREATE TABLE tests (id SERIAL PRIMARY KEY, uuid_col UUID);
NOTICE:  using sequential values in a primary key does not perform as well as using random UUIDs. See https://www.cockroachlabs.com/docs/v22.1/serial.html
CREATE TABLE
test_uuid_like=> SELECT * FROM tests;
 id | uuid_col
----+----------
(0 rows)

test_uuid_like=> SELECT * FROM tests WHERE uuid_col LIKE 'fff*';
ERROR:  unsupported comparison operator: <uuid> LIKE <string>
```